/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Cliente.*;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
/**
 *
 * @author Tulea4ever
 */
public class Login extends javax.swing.JFrame {
    
    ManagerCliente cliente = new ManagerCliente();
    JsonManagerCliente JSC = new JsonManagerCliente();
    Globales datos = new Globales();
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        entryContraseña = new javax.swing.JPasswordField();
        entryUsuario = new javax.swing.JTextField();
        logoUser1 = new javax.swing.JLabel();
        LogoPasswd1 = new javax.swing.JLabel();
        BotonIngresar = new javax.swing.JButton();
        nombre2 = new javax.swing.JLabel();
        nombre3 = new javax.swing.JLabel();
        textoIngresar1 = new javax.swing.JLabel();
        mensajeError = new javax.swing.JLabel();
        buttonRegistrar1 = new javax.swing.JButton();
        Fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entryContraseña.setBackground(new java.awt.Color(102, 102, 102));
        entryContraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        entryContraseña.setText("Contras");
        entryContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryContraseñaActionPerformed(evt);
            }
        });
        panelLogin.add(entryContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 410, 60));

        entryUsuario.setBackground(new java.awt.Color(102, 102, 102));
        entryUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        entryUsuario.setText("Usuario");
        entryUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryUsuarioActionPerformed(evt);
            }
        });
        panelLogin.add(entryUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 410, 60));

        logoUser1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tulea4ever\\Downloads\\logo user.png")); // NOI18N
        panelLogin.add(logoUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        LogoPasswd1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tulea4ever\\Downloads\\logoPasswd.png")); // NOI18N
        panelLogin.add(LogoPasswd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        BotonIngresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tulea4ever\\Downloads\\login.png")); // NOI18N
        BotonIngresar.setOpaque(false);
        BotonIngresar.setContentAreaFilled(false);
        BotonIngresar.setBorderPainted(false);
        BotonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonIngresarMouseClicked(evt);
            }
        });
        BotonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIngresarActionPerformed(evt);
            }
        });
        panelLogin.add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, -1, -1));

        nombre2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        nombre2.setForeground(new java.awt.Color(255, 255, 255));
        nombre2.setText("EL BUEN PROYECTO");
        panelLogin.add(nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 500, -1));

        nombre3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        nombre3.setForeground(new java.awt.Color(255, 255, 255));
        nombre3.setText("Libreria");
        panelLogin.add(nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 170, -1));

        textoIngresar1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textoIngresar1.setForeground(new java.awt.Color(255, 255, 255));
        textoIngresar1.setText("INGRESAR");
        panelLogin.add(textoIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 100, 30));

        mensajeError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mensajeError.setForeground(new java.awt.Color(255, 0, 0));
        mensajeError.setText("Usuario o contraseña incorrecto, verifica los datos.");
        panelLogin.add(mensajeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 410, 20));
        mensajeError.setEnabled(false);

        buttonRegistrar1.setBackground(new java.awt.Color(204, 204, 204));
        buttonRegistrar1.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        buttonRegistrar1.setForeground(new java.awt.Color(0, 0, 0));
        buttonRegistrar1.setText("Registrarse");
        buttonRegistrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRegistrar1MouseClicked(evt);
            }
        });
        panelLogin.add(buttonRegistrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 160, 30));

        Fondo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tulea4ever\\Downloads\\libreria.jpg")); // NOI18N
        panelLogin.add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelLogin.setEnabled(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryContraseñaActionPerformed

    private void entryUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryUsuarioActionPerformed

    private void BotonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIngresarMouseClicked
        login();
    }//GEN-LAST:event_BotonIngresarMouseClicked

    private void BotonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonIngresarActionPerformed

    private void buttonRegistrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRegistrar1MouseClicked
        registrar();
       
    }//GEN-LAST:event_buttonRegistrar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel LogoPasswd1;
    private javax.swing.JButton buttonRegistrar1;
    private javax.swing.JTextField entryContraseña;
    private javax.swing.JTextField entryUsuario;
    private javax.swing.JLabel logoUser1;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JLabel nombre2;
    private javax.swing.JLabel nombre3;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JLabel textoIngresar1;
    // End of variables declaration//GEN-END:variables

    //FUNCION PARA LOGEARSE
    public void login(){
        
        //ALMACENAMIENTO DE LOS DATOS INGRESADOS
        String nombre = entryUsuario.getText();
        String passwd = entryContraseña.getText();
        JSONObject JS = JSC.Jsonlogin(nombre,passwd);
        //ESPERANDO RESPUESTA DEL SERVIDOR PARA CONTINUAR
        if(cliente.sendSesion(JS.toString())){
            GuiPrincipal(JSC.JsonID(nombre,passwd));
        }
        else {mensajeError.setEnabled(true);}
    }
    
    //FUNCION PARA DESPLEGAR VENTANA DE REGISTRO
    public void registrar(){
        dispose();
        Registro v = new Registro();
        v.setVisible(true);
    }
    
    //FUNCION PARA DESPLEGAR VENTANA PRINCIPAL LUEGO DE LOGEAR
    public void GuiPrincipal(JSONObject JS){
        //CERRAR LA VENTANA ACTUAL
        dispose();
        //CREAR LA VENTANA PRINCIPAL
        Principal v = new Principal();
        v.setVisible(true);
        //TRANSMITIR LOS DATOS DEL USUARIO
        datos.setCod_usuario(cliente.idUsuario(JS.toString()));
        datos.setNombre(entryUsuario.getText());
        v.globales(datos);
    }
    
    //FUNCION PARA CERRAR CORRECTAMENTE
    public void cerrarVentana(){
        System.exit(0);
    }
}
