/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author Tulea4ever
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        entryContraseña = new javax.swing.JPasswordField();
        entryUsuario = new javax.swing.JTextField();
        logoUser = new javax.swing.JLabel();
        LogoPasswd = new javax.swing.JLabel();
        BotonIngresar = new javax.swing.JButton();
        nombre1 = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        textoIngresar = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        panelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entryContraseña.setBackground(new java.awt.Color(102, 102, 102));
        entryContraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        entryContraseña.setText("Contraseña");
        entryContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryContraseñaActionPerformed(evt);
            }
        });
        panelLogin.add(entryContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 410, 60));

        entryUsuario.setBackground(new java.awt.Color(102, 102, 102));
        entryUsuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        entryUsuario.setText("Usuario");
        entryUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryUsuarioActionPerformed(evt);
            }
        });
        panelLogin.add(entryUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 410, 60));

        logoUser.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tulea4ever\\Downloads\\logo user.png")); // NOI18N
        panelLogin.add(logoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        LogoPasswd.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tulea4ever\\Downloads\\logoPasswd.png")); // NOI18N
        panelLogin.add(LogoPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, -1, -1));

        BotonIngresar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tulea4ever\\Downloads\\login.png")); // NOI18N
        BotonIngresar.setOpaque(false);
        BotonIngresar.setContentAreaFilled(false);
        BotonIngresar.setBorderPainted(false);
        panelLogin.add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, -1, -1));

        nombre1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        nombre1.setForeground(new java.awt.Color(255, 255, 255));
        nombre1.setText("EL BUEN PROYECTO");
        panelLogin.add(nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 500, -1));

        nombre.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        nombre.setForeground(new java.awt.Color(255, 255, 255));
        nombre.setText("Libreria");
        panelLogin.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 170, -1));

        textoIngresar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textoIngresar.setForeground(new java.awt.Color(255, 255, 255));
        textoIngresar.setText("INGRESAR");
        panelLogin.add(textoIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 690, 100, 30));

        Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tulea4ever\\Downloads\\libreria.jpg")); // NOI18N
        panelLogin.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryContraseñaActionPerformed

    private void entryUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel LogoPasswd;
    private javax.swing.JTextField entryContraseña;
    private javax.swing.JTextField entryUsuario;
    private javax.swing.JLabel logoUser;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel nombre1;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JLabel textoIngresar;
    // End of variables declaration//GEN-END:variables
}
