/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Cliente.Archivo;
import Cliente.Globales;
import Cliente.JsonManagerCliente;
import Cliente.ManagerCliente;
import java.awt.Color;
import java.awt.Font;
import org.json.simple.JSONObject;
import javax.swing.*;
import javax.swing.table.*;
import java.util.concurrent.TimeUnit;
import Herencia.*;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

/**
 *
 * @author Tulea4ever
 */
public final class Principal extends javax.swing.JFrame implements Archivo{
    
    private String codigoUsuario,action;
    private Globales datos = new Globales();
    ManagerCliente cliente = new ManagerCliente();
    JsonManagerCliente JSC = new JsonManagerCliente();
    
    /**
     * Creates new form GuiPrincipal
     */
    public Principal() {
        initComponents();
        
        //apagarPaneles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        PanelPrincipal = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        buttonAlquilar = new javax.swing.JButton();
        buttonDevolver = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        Label_nombre = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panellateral = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        setName("Libreria"); // NOI18N

        tabla.setBackground(new java.awt.Color(153, 204, 255));
        tabla.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        tabla.setForeground(new java.awt.Color(0, 0, 0));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "EDITORIAL", "ESTADO"
            }
        ));
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla.setShowVerticalLines(false);
        //jTable1.setRowSelectionAllowed(false);
        jScrollPane1.setViewportView(tabla);

        buttonAlquilar.setText("ALQUILAR");
        buttonAlquilar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAlquilarMouseClicked(evt);
            }
        });

        buttonDevolver.setText("DEVOLVER");
        buttonDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonDevolverMouseClicked(evt);
            }
        });
        buttonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDevolverActionPerformed(evt);
            }
        });

        PanelPrincipal.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelPrincipal.setLayer(buttonAlquilar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        PanelPrincipal.setLayer(buttonDevolver, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonAlquilar)
                    .addComponent(buttonDevolver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonDevolver)
                .addGap(18, 18, 18)
                .addComponent(buttonAlquilar)
                .addGap(87, 87, 87))
        );

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Copyright");

        jDesktopPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user_1.png"))); // NOI18N

        Label_nombre.setBackground(new java.awt.Color(255, 255, 255));
        Label_nombre.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        Label_nombre.setForeground(new java.awt.Color(255, 255, 255));
        Label_nombre.setText("NOMBRE");
        Label_nombre.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/5a1c2855373082.9276742415117947732261.png"))); // NOI18N

        jDesktopPane2.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(Label_nombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Label_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Label_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LIBROS");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setVerifyInputWhenFocusTarget(false);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("REVISTAS");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel7.setVerifyInputWhenFocusTarget(false);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ALQUILERES");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel8.setVerifyInputWhenFocusTarget(false);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SALIR");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel9.setVerifyInputWhenFocusTarget(false);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        panellateral.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panellateral.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panellateral.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panellateral.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panellateralLayout = new javax.swing.GroupLayout(panellateral);
        panellateral.setLayout(panellateralLayout);
        panellateralLayout.setHorizontalGroup(
            panellateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panellateralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panellateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panellateralLayout.setVerticalGroup(
            panellateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panellateralLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 491, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDesktopPane2)
                    .addComponent(jSeparator1)
                    .addComponent(jDesktopPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(panellateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panellateral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       libros();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        revistas();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void buttonAlquilarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAlquilarMouseClicked
        alquilar(action);
    }//GEN-LAST:event_buttonAlquilarMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        alquileres();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void buttonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDevolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDevolverActionPerformed

    private void buttonDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonDevolverMouseClicked
        actionDevolver();
    }//GEN-LAST:event_buttonDevolverMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_nombre;
    private javax.swing.JDesktopPane PanelPrincipal;
    private javax.swing.JButton buttonAlquilar;
    private javax.swing.JButton buttonDevolver;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JDesktopPane panellateral;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

    //APAGAR LOS PANELES NO NECESARIOS
public void apagarPaneles(){
    PanelPrincipal.setVisible(false);
    tabla.setVisible(false); 
}

//FUNCION PARA IGUALAR DATOS DE GLOBALES CON EL LOGIN
public void globales(){
    leerArchivo();
    Label_nombre.setText(datos.getNombre());  
}

//FUNCION PARA TRAER DATOS DEL SERVIDOR E INSERTARLOS EN LA TABLE
public void libros(){
    //VISUALIZACION DEL BOTON CORRECTO 
    buttonDevolver.setVisible(false);
    buttonAlquilar.setVisible(true);
    borrarTabla();
    //CREACION DEL MODELO
    DefaultTableModel modelo = cliente.sendReceivesLibros(JSC.Jsonlibros().toString());
    //INSERCION DEL MODELO EN LA TABLA CON LOS DATOS
    tabla.setModel(modelo);
    //PASO DE ACCION A LIBROS
    action = "libros";
}

//FUNCION PARA VISUALIZACION DE REVISTAS
public void revistas(){
    //VISUALIZAR EL BOTON CORRECTO
    buttonDevolver.setVisible(false);
    buttonAlquilar.setVisible(true);
    borrarTabla();
    //DECLARACION DEL MODELO CON LOS DATOS DEL SERVIDOR
    DefaultTableModel modelo = cliente.sendReceivesRevistas(JSC.JsonRevistas().toString());
    //new Thread(fill(100));
    //INSERSION DEL MODELO A LA TABLA
    tabla.setModel(modelo);
    //DECLARAR LA ACCION A REVISTAS
    action = "revistas";
}

//FUNCION PARA RECIBIR LOS ALQUILERES ACTIVOS
public void alquileres(){
    //VISUALIZAR BOTON CORRECTO
    buttonDevolver.setVisible(true);
    buttonAlquilar.setVisible(false);
    borrarTabla();
    //INSERT DE LOS DATOS DEL SERVIDOR AL MODELO
    DefaultTableModel modelo = cliente.sendReceivesAlquileres
        (JSC.JsonAlquileres(Label_nombre.getText()).toString());
    //new Thread(fill(100));
    //INSERTAR MODELO A LA TABLA PARA SU VISUALIZACION
    tabla.setModel(modelo);
    
}

//ELIMINAR LA TABLA ACTUAL PARA NUEVA VISUALIZACION
public void borrarTabla(){
    //SE DECLARA MODELO NUEVO
    DefaultTableModel modelo = (DefaultTableModel)tabla.getModel(); 
    //SE LIMPIA MEDIANTE BUCLE WHILE
    while(modelo.getRowCount() > 0) 
        { modelo.removeRow(0); }
    

}

//FUNCION PARA MOSTRAR BARRA DE PROGRESO
public String fill(int tiempo){
        
    //CREACION DE LA BARRA
        JProgressBar bar = new JProgressBar();
        bar.setValue(0);
        bar.setVisible(true);
        bar.setBounds(0,0,1266,50);
        //bar.setStringPainted(true);
        bar.setFont(new Font("MV Boli",Font.BOLD,25));
        //AñADIRMLA AL OBJETO JFRAME
        jDesktopPane1.add(bar);
        int count = 0;
        //SIMULAR LA CARGA DE DATOS
        while(count <=100){
            bar.setValue(count);
            
            try{
                Thread.sleep(tiempo);
            }catch(Exception e){}
            count +=10;
        }   
        
        
        try{
                Thread.sleep(1500);
                bar.setVisible(false);
            }catch(Exception e){}
            count +=10;
        
        return "f";
    }

//FUNCION PARA EL BOTON DE ALQUILAR
public void alquilar(String action){
    
    try{
        //DEFINIR LA LINEA SELECCIONADA EN LA TABLA
        int row = tabla.getSelectedRow();
        //DECLARAR SI ES UN LIBRO O REVISTA
        if (action.equalsIgnoreCase("libros")){
            Libro libro = new Libro(tabla.getModel().getValueAt(row, 0).toString(),
                                    tabla.getModel().getValueAt(row, 1).toString(),
                                    tabla.getModel().getValueAt(row, 2).toString());
            //MUESTRA VENTANA DE ALQUILER
            Alquilar alquiler = new Alquilar();
            alquiler.setVisible(true);
            //REALIZA LA SELECCION DE ACCION PARA VISUALIZAR VENTANA
            alquiler.action(libro, datos.getNombre());
            libros();
        }
        //EJECUTA SI ES REVISTA
        else{
                Revista revista = new Revista(tabla.getModel().getValueAt(row, 0).toString(),
                                    tabla.getModel().getValueAt(row, 1).toString(),
                                    tabla.getModel().getValueAt(row, 2).toString(),
                                    tabla.getModel().getValueAt(row, 3).toString());
                //CREA LA VENTANA DE ALQUILERES
                Alquilar alquiler = new Alquilar();
                alquiler.setVisible(true);
                //DEFINE LOS COMPONENTES A VISUALIZAR DE LA VENTANA ANTERIOR
                alquiler.action(revista, datos.getNombre());
                revistas();
        }
        
    }catch(Exception e){JOptionPane.showMessageDialog(null, "Seleccione una fila a alquilar");}
}

//FUNCION PARA EL BOTON DE DEVOLVER
public void actionDevolver(){
    
    try{

        //DEFINE LA LINEA SELECCIONADA DE LA TABLA
        int row = tabla.getSelectedRow();
        //EXTRAE LOS DATOS SELECCIONADOS DE LA TABLA
        if (tabla.getModel().getValueAt(row, 5).toString().equalsIgnoreCase("libros")){
            Libro libro = new Libro(tabla.getModel().getValueAt(row, 0).toString(),
                                    tabla.getModel().getValueAt(row, 1).toString(),
                                    tabla.getModel().getValueAt(row, 2).toString());
            //CREA LA VENTANA DE DEVOLUCION
            Alquilar alquiler = new Alquilar();
            alquiler.setVisible(true);
            //DECLARA LA VENTANA CON LOS COMPONENTES PARA LIBROS
            alquiler.devolver(libro, datos.getNombre(),tabla.getModel().getValueAt(row, 6).toString());
            libros();
        }
        else{//EJECUTA SI ES UNA REVISTA
                Revista revista = new Revista(tabla.getModel().getValueAt(row, 0).toString(),
                                    tabla.getModel().getValueAt(row, 1).toString(),
                                    tabla.getModel().getValueAt(row, 2).toString(),
                                    tabla.getModel().getValueAt(row, 3).toString());
                //CREA LA VENTANA DE DEVOLUCION
                Alquilar alquiler = new Alquilar();
                alquiler.setVisible(true);
                //DELCARA LOS COMPONENTES VISUALES DE LA VENTANA PARA REVISTA
                alquiler.devolver(revista, datos.getNombre(),tabla.getModel().getValueAt(row, 6).toString());
                revistas();
        }
        
    }catch(Exception e){JOptionPane.showMessageDialog(null, "Seleccione una fila a devolver");}
}

    //POLIFORMISMO INTERFACE
    @Override
    public void leerArchivo(){
        //DECLARACION DE VARIABLES NECESARIAS
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;

        try {//DECLARACION DE LA RUTA DE NUESTRO ARCHIVO
            String ruta = "..\\globales.txt";
            archivo = new File (ruta);
            fr = new FileReader (archivo);
            br = new BufferedReader(fr);

            //LECTURA DEL ARCHIVO
            int vuelta = 0;
            while((br.readLine())!=null)
                //INSERTAR LOS DATOS RECOLECTADOS EN LA INTERFACE GRAFICA
                if (vuelta == 1){
                    datos.setNombre(br.readLine());
                }else{datos.setNombre(br.readLine());}
            vuelta++;
        }
        catch(Exception e){
           e.printStackTrace();
        }finally{//CERRAR ARCHIVO SI O SI
           
           try{                    
              if( null != fr ){   
                 fr.close();     
              }                  
           }catch (Exception e2){ 
              e2.printStackTrace();
           }
      }
    }
    //POLIFORMISMO INTERFACE
    @Override
    public void crearArchivo(){}
}



