/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Cliente.JsonManagerCliente;
import Cliente.ManagerCliente;
import org.json.simple.JSONObject;
import Cliente.*;


/**
 *
 * @author Tulea4ever
 */
public class Registro extends javax.swing.JFrame {
    
    ManagerCliente cliente = new ManagerCliente();
    JsonManagerCliente JSC = new JsonManagerCliente();
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelRegistro = new javax.swing.JPanel();
        panelRegistro = new javax.swing.JPanel();
        entryRpasswd = new javax.swing.JTextField();
        BotonIngresar = new javax.swing.JButton();
        textoIngresar = new javax.swing.JLabel();
        mensajeError = new javax.swing.JLabel();
        entryRusuario = new javax.swing.JTextField();
        buttonLogin = new javax.swing.JButton();
        jLabelRP = new javax.swing.JLabel();
        jLabelRU = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelRegistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entryRpasswd.setBackground(new java.awt.Color(102, 102, 102));
        entryRpasswd.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        panelRegistro.add(entryRpasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 330, 40));

        BotonIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/register.png"))); // NOI18N
        BotonIngresar.setOpaque(false);
        BotonIngresar.setContentAreaFilled(false);
        BotonIngresar.setBorderPainted(false);
        BotonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonIngresarMouseClicked(evt);
            }
        });
        panelRegistro.add(BotonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 90, 70));

        textoIngresar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        textoIngresar.setForeground(new java.awt.Color(255, 255, 255));
        textoIngresar.setText("Registrarse");
        panelRegistro.add(textoIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 100, 30));

        mensajeError.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mensajeError.setForeground(new java.awt.Color(255, 0, 0));
        mensajeError.setText("Error al registar, puede que el usuario ya existe ...");
        panelRegistro.add(mensajeError, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 410, 20));
        mensajeError.setEnabled(false);

        entryRusuario.setBackground(new java.awt.Color(102, 102, 102));
        entryRusuario.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        panelRegistro.add(entryRusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 330, 40));

        buttonLogin.setBackground(new java.awt.Color(204, 204, 204));
        buttonLogin.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(0, 0, 0));
        buttonLogin.setText("Iniciar Sesion");
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginMouseClicked(evt);
            }
        });
        panelRegistro.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 160, 30));

        jLabelRP.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabelRP.setText("Ingrese la contraseña:");
        panelRegistro.add(jLabelRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 210, 30));

        jLabelRU.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabelRU.setText("Ingrese el nombre de usuario:");
        panelRegistro.add(jLabelRU, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 210, 30));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistro.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 560, 10));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        panelRegistro.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 560, 10));

        Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Tulea4ever\\Downloads\\libreria.jpg")); // NOI18N
        panelRegistro.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 790));

        javax.swing.GroupLayout PanelRegistroLayout = new javax.swing.GroupLayout(PanelRegistro);
        PanelRegistro.setLayout(PanelRegistroLayout);
        PanelRegistroLayout.setHorizontalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelRegistroLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        PanelRegistroLayout.setVerticalGroup(
            PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(PanelRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelRegistroLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(PanelRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseClicked
        login();
    }//GEN-LAST:event_buttonLoginMouseClicked

    private void BotonIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonIngresarMouseClicked
       Registrar();
    }//GEN-LAST:event_BotonIngresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonIngresar;
    private javax.swing.JLabel Fondo;
    private javax.swing.JPanel PanelRegistro;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JTextField entryRpasswd;
    private javax.swing.JTextField entryRusuario;
    private javax.swing.JLabel jLabelRP;
    private javax.swing.JLabel jLabelRU;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel mensajeError;
    private javax.swing.JPanel panelRegistro;
    private javax.swing.JLabel textoIngresar;
    // End of variables declaration//GEN-END:variables

    //FUNCION PARA DESPLEGAR VENTANA LOGIN
    public void login(){
        dispose();
        Login v = new Login();
        v.setVisible(true);

    }
    
    //FUNCION PARA CONECTAR CON SERVIDOR Y REGISTRAR USUARIO
    public void Registrar(){
        //DECLARACION DE LOS DATOS INSERTADOS
        String nombre = entryRusuario.getText();
        String passwd = entryRpasswd.getText();
        //VERIFICACION QUE LOS DATOS NO SEAN VACIOS
        if (!nombre.equalsIgnoreCase("") && !passwd.equalsIgnoreCase("")){
            //CREACION DEL JSON ENVIADO AL SERVIDOR
            JSONObject JS = JSC.JsonRegistration(nombre,passwd);
            //ENVIA AL SERVIDOR Y ESPERA RESPUESTA PARA CONTINUAR
            if(cliente.sendSesion(JS.toString())){
               login();
            }//SI EL SERVIDOR NO DIO CONEXION EXITOSA
            else {mensajeError.setEnabled(true);
            }
        }else {mensajeError.setEnabled(true);}
    }
    
}
